-- MySQL Script generated by MySQL Workbench
-- Wed Apr  7 11:36:03 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`locations` ;

CREATE TABLE IF NOT EXISTS `mydb`.`locations` (
  `id` INT(11) NOT NULL,
  `etagere` VARCHAR(250) NOT NULL,
  `niveau` INT(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 78
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`products` ;

CREATE TABLE IF NOT EXISTS `mydb`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `ncas` VARCHAR(250) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `location_id` INT(11) NOT NULL,
  `is_open` TINYINT NULL DEFAULT 0,
  `is_used` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_locations1_idx` (`location_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_locations1`
    FOREIGN KEY (`location_id`)
    REFERENCES `mydb`.`locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 81
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`chemical_safeties`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`chemical_safeties` ;

CREATE TABLE IF NOT EXISTS `mydb`.`chemical_safeties` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(250) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`roles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(50) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `role_id` INT NOT NULL,
  `password` VARCHAR(250) NULL,
  PRIMARY KEY (`id`),
  INDEX `utilisateur-role` (`role_id` ASC) VISIBLE,
  CONSTRAINT `utilisateur-role`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`roles` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 74
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`chemical_safety_property`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`chemical_safety_property` ;

CREATE TABLE IF NOT EXISTS `mydb`.`chemical_safety_property` (
  `products_id` INT NOT NULL,
  `properties_id` INT(11) NOT NULL,
  PRIMARY KEY (`products_id`, `properties_id`),
  INDEX `fk_products_has_properties_properties1_idx` (`properties_id` ASC) VISIBLE,
  INDEX `fk_products_has_properties_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_has_properties_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `mydb`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_properties_properties1`
    FOREIGN KEY (`properties_id`)
    REFERENCES `mydb`.`chemical_safeties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`incompatibilities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`incompatibilities` ;

CREATE TABLE IF NOT EXISTS `mydb`.`incompatibilities` (
  `chemical_safeties_id` INT(11) NOT NULL,
  `chemical_safeties_id1` INT(11) NOT NULL,
  PRIMARY KEY (`chemical_safeties_id`, `chemical_safeties_id1`),
  INDEX `fk_chemical_safeties_has_chemical_safeties_chemical_safetie_idx` (`chemical_safeties_id1` ASC) VISIBLE,
  INDEX `fk_chemical_safeties_has_chemical_safeties_chemical_safetie_idx1` (`chemical_safeties_id` ASC) VISIBLE,
  CONSTRAINT `fk_chemical_safeties_has_chemical_safeties_chemical_safeties1`
    FOREIGN KEY (`chemical_safeties_id`)
    REFERENCES `mydb`.`chemical_safeties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chemical_safeties_has_chemical_safeties_chemical_safeties2`
    FOREIGN KEY (`chemical_safeties_id1`)
    REFERENCES `mydb`.`chemical_safeties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `mydb`.`product_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`product_user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`product_user` (
  `products_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`products_id`, `users_id`),
  INDEX `fk_products_has_users_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_products_has_users_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_has_users_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `mydb`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_users_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
