security:
#    access_denied_url: login

    enable_authenticator_manager: true

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: registration_number
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            context: my_context
            provider: user_provider
            access_denied_handler: App\Security\AccessDeniedHandler
            guard:
                authenticators:
                    - App\Security\AppAdminAuthenticator
#            custom_authenticators:
#                - App\Security\TestAuthenticator
            logout:
                path: app_logout

        main:
            context: my_context

            provider: user_provider
            #            remember_me:
            #                secret: '%kernel.secret%'
            #                lifetime: 604800 # 1 week in seconds
            #                path: /
            guard:
                authenticators:
                    - App\Security\AppCustomAuthenticator
#            custom_authenticators:
#                - App\Security\TestSimpleAuthenticator
            logout:
                path: app_logout
                  # where to redirect after logout
                # target: products.index



    access_control:
        - { path: ^/admin/login$, roles: PUBLIC_ACCESS }
        - { path: ^/admin/, roles: ROLE_ADMIN }










#security:
#
#
#    role_hierarchy:
#        ROLE_ADMIN: ROLE_USER
#        ROLE_SUPER_ADMIN: ROLE_ADMIN
#
#    encoders:
#        App\Entity\User:
#            algorithm: auto
#
#    providers:
#        user_provider:
#            entity:
#                class: App\Entity\User
#                property: registration_number
#    firewalls:
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        admin:
#            pattern: ^/admin/
#            context: ulims-security
#            provider: user_provider
#
#            anonymous: true
#            lazy: true
#
#            guard:
#                authenticators:
#                    - App\Security\AppAdminAuthenticator
#
#            logout:
#                path: app_logout
#                target: products.index
#
##        main:
##            context: ulims-security
##            provider: user_provider
###            anonymous: true
##            lazy: true
##            guard:
##                authenticators:
##                    - App\Security\AppCustomAuthenticator
##
##            logout:
##                path: app_logout
##                target: products.index
#
#    access_control:
#        - { path: ^/admin/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin/, roles: ROLE_ADMIN }
#







#security:
#
#    enable_authenticator_manager: true
#
#    role_hierarchy:
#        ROLE_ADMIN: ROLE_USER
#        ROLE_SUPER_ADMIN: ROLE_ADMIN
#
#    encoders:
#        App\Entity\User:
#            algorithm: auto
#
#    providers:
#        user_provider:
#            entity:
#                class: App\Entity\User
#                property: registration_number
#    firewalls:
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        admin:
#            pattern: ^/admin/
#            context: ulims-security
#            provider: user_provider
#            custom_authenticators:
#                - App\Security\TestAuthenticator
#
#            logout:
#                path: app_logout
#                target: products.index
#
#        main:
#            context: ulims-security
#            provider: user_provider
#            custom_authenticators:
#                - App\Security\TestSimpleAuthenticator
#
#            logout:
#                path: app_logout
#                target: products.index
#
#
#
#
#
#    access_control:
#        - { path: ^/admin/login$, roles: PUBLIC_ACCESS }
#        - { path: ^/admin/, roles: ROLE_ADMIN }
#
#






