#https://hub.docker.com/_/mysql/
version: '2'
services:
    db:
        image: mysql:8.0.24 #version used during the implementation of the project 
        container_name: mysql 
        ports:
          - 3306:3306
        environment:
          MYSQL_ROOT_PASSWORD: f5dU7a8UjkgUc0dUd
          MYSQL_USER: uumons_lims
          MYSQL_PASSWORD: u_litpas21
          MYSQL_DATABASE: umons_lims

    php:
        build: php7-fpm
        ports:
            - 9000:9000
        #command: bash -c "myentrypoint.sh"
        links:
            - db
        volumes:
            - ../umons-lims2:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
        depends_on:
          - db
        environment:
          - WAIT_HOSTS=mysql:3306
          - WAIT_SLEEP_INTERVAL=15
          - MYSQL_DATABASE=umons_lims
          - MYSQL_USER=uumons_lims
          - MYSQL_PASSWORD=u_litpas21

    nginx:
        build: nginx
        ports:
          - 80:80
        links:
          - php
        volumes_from:
          - php
        volumes:
          - ./logs/nginx/:/var/log/nginx
        depends_on:
          - php
          - db
        environment:
          - WAIT_HOSTS=mysql:3306, php:9000
          - WAIT_SLEEP_INTERVAL=20
          - WAIT_TIMEOUT=60